# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2023-02-24 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
            ],
        ),
    ]
