# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2023-02-24 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
            ],
        ),
    ]
