# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2023-02-25 05:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
            ],
        ),
    ]
