# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2023-02-27 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_questions1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions2',
            fields=[
            ],
        ),
    ]
